### ISSUE TITLE
Support for 2019 

### ISSUE THREAD

**Issue by fgregg** [jsfenfen/990-xml-database#23]
When trying to add 2019 data, I get the following traceback:

```bash
Traceback (most recent call last):
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/irsx/filing.py", line 88, in _set_dict_from_xml
    self.raw_irs_dict['Return']
KeyError: 'Return'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fgregg/work/990-xml-database/irsdb/return/management/commands/load_filings.py", line 61, in run_filing
    parsed_filing = self.xml_runner.run_filing(object_id)
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/irsx/xmlrunner.py", line 111, in run_filing
    this_filing.process(verbose=verbose)
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/irsx/filing.py", line 202, in process
    self._set_dict_from_xml()
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/irsx/filing.py", line 94, in _set_dict_from_xml
    self.filepath
irsx.filing.InvalidXMLException: ("'Return' element not located intemp/XML/201940149349301304_public.xml\nFile may be damaged or incomplete.\nTry erasing this file and downloading again.", 'temp/XML/201940149349301304_public.xml')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/irsx/filing.py", line 88, in _set_dict_from_xml
    self.raw_irs_dict['Return']
KeyError: 'Return'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/fgregg/work/990-xml-database/irsdb/return/management/commands/load_filings.py", line 124, in handle
    self.run_filing(filing)
  File "/Users/fgregg/work/990-xml-database/irsdb/return/management/commands/load_filings.py", line 64, in run_filing
    parsed_filing = self.xml_runner.run_filing(object_id)
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/irsx/xmlrunner.py", line 111, in run_filing
    this_filing.process(verbose=verbose)
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/irsx/filing.py", line 202, in process
    self._set_dict_from_xml()
  File "/Users/fgregg/work/990-xml-database/.env/lib/python3.7/site-packages/irsx/filing.py", line 94, in _set_dict_from_xml
    self.filepath
irsx.filing.InvalidXMLException: ("'Return' element not located intemp/XML/201940149349301304_public.xml\nFile may be damaged or incomplete.\nTry erasing this file and downloading again.", 'temp/XML/201940149349301304_public.xml')
```

But the xml file looks well formed.

```xml
<?xml version="1.0" encoding="utf-8"?>
<irs:Return returnVersion="2017v2.2" xmlns="http://www.irs.gov/efile" xmlns:irs="http://www.irs.gov/efile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <irs:ReturnHeader binaryAttachmentCnt="0">
    <irs:ReturnTs>2019-01-08T17:22:08-08:00</irs:ReturnTs>
    <irs:TaxPeriodEndDt>2017-12-31</irs:TaxPeriodEndDt>
    <irs:PreparerFirmGrp>
      <irs:PreparerFirmEIN>453945095</irs:PreparerFirmEIN>
      <irs:PreparerFirmName>
        <irs:BusinessNameLine1Txt>TAXPRO OF TAMPA</irs:BusinessNameLine1Txt>
      </irs:PreparerFirmName>
      <irs:PreparerUSAddress>
        <irs:AddressLine1Txt>3420S DALE MARBY HWY STE S</irs:AddressLine1Txt>
        <irs:CityNm>TAMPA</irs:CityNm>
        <irs:StateAbbreviationCd>FL</irs:StateAbbreviationCd>
        <irs:ZIPCd>33629</irs:ZIPCd>
      </irs:PreparerUSAddress>
    </irs:PreparerFirmGrp>
    <irs:ReturnTypeCd>990</irs:ReturnTypeCd>
    <irs:TaxPeriodBeginDt>2017-01-01</irs:TaxPeriodBeginDt>
    <irs:Filer>
      <irs:EIN>811338606</irs:EIN>
      <irs:BusinessName>
        <irs:BusinessNameLine1Txt>DREAM BUILDERS MISSION</irs:BusinessNameLine1Txt>
      </irs:BusinessName>
      <irs:BusinessNameControlTxt>DREA</irs:BusinessNameControlTxt>
      <irs:USAddress>
        <irs:AddressLine1Txt>8145 NEBRASKA AVENUE</irs:AddressLine1Txt>
        <irs:CityNm>TAMPA</irs:CityNm>
        <irs:StateAbbreviationCd>FL</irs:StateAbbreviationCd>
        <irs:ZIPCd>33604</irs:ZIPCd>
      </irs:USAddress>
    </irs:Filer>
    <irs:BusinessOfficerGrp>
      <irs:PersonNm>HARRISON SOBERANIS</irs:PersonNm>
      <irs:PersonTitleTxt>EXEC DIRECTOR</irs:PersonTitleTxt>
      <irs:PhoneNum>8134451697</irs:PhoneNum>
      <irs:SignatureDt>2018-05-22</irs:SignatureDt>
    </irs:BusinessOfficerGrp>
    <irs:PreparerPersonGrp>
      <irs:PreparerPersonNm>MICHELLE JAMES</irs:PreparerPersonNm>
      <irs:PTIN>P00515590</irs:PTIN>
      <irs:PhoneNum>8138316100</irs:PhoneNum>
      <irs:PreparationDt>2018-05-22</irs:PreparationDt>
    </irs:PreparerPersonGrp>
    <irs:FilingSecurityInformation>
      <irs:IPAddress>
        <irs:IPv4AddressTxt>108.191.141.088</irs:IPv4AddressTxt>
      </irs:IPAddress>
      <irs:FilingLicenseTypeCd>P</irs:FilingLicenseTypeCd>
      <irs:AtSubmissionCreationDeviceId>D74A9EB7C2BD0DD620C750DDF6730E26D7C61A42</irs:AtSubmissionCreationDeviceId>
      <irs:AtSubmissionFilingDeviceId>5D4D74A5677236E8869404A8E3FC63E63CF3CC48</irs:AtSubmissionFilingDeviceId>
    </irs:FilingSecurityInformation>
    <irs:TaxYr>2017</irs:TaxYr>
    <irs:BuildTS>2019-02-21 02:37:17Z</irs:BuildTS>
  </irs:ReturnHeader>
  <irs:ReturnData documentCnt="3">
    <irs:IRS990 documentId="USXX01">
      <irs:InitialReturnInd>X</irs:InitialReturnInd>
      <irs:AmendedReturnInd>X</irs:AmendedReturnInd>
      <irs:PrincipalOfficerNm>HARRISON SOBERANIS</irs:PrincipalOfficerNm>
      <irs:USAddress>
        <irs:AddressLine1Txt>8145 NEBRASKA AVENUE</irs:AddressLine1Txt>
        <irs:CityNm>TAMPA</irs:CityNm>
        <irs:StateAbbreviationCd>FL</irs:StateAbbreviationCd>
        <irs:ZIPCd>33604</irs:ZIPCd>
      </irs:USAddress>
      <irs:GrossReceiptsAmt>27459</irs:GrossReceiptsAmt>
      <irs:GroupReturnForAffiliatesInd>false</irs:GroupReturnForAffiliatesInd>
      <irs:Organization501c3Ind>X</irs:Organization501c3Ind>
      <irs:TypeOfOrganizationCorpInd>X</irs:TypeOfOrganizationCorpInd>
      <irs:FormationYr>2017</irs:FormationYr>
      <irs:LegalDomicileStateCd>FL</irs:LegalDomicileStateCd>
      <irs:ActivityOrMissionDesc>THE ORGANIZATION'S PRIMARY FOCUS IS TO REACH OUT TO THE HOMELESS AND HUNGRY IN THE COMMUNITY AND PROMOTE SELF-SUFFICIENCY.</irs:ActivityOrMissionDesc>
      <irs:VotingMembersGoverningBodyCnt>0</irs:VotingMembersGoverningBodyCnt>
      <irs:VotingMembersIndependentCnt>0</irs:VotingMembersIndependentCnt>
      <irs:TotalEmployeeCnt>0</irs:TotalEmployeeCnt>
      <irs:TotalVolunteersCnt>5</irs:TotalVolunteersCnt>
      <irs:TotalGrossUBIAmt>0</irs:TotalGrossUBIAmt>
      <irs:CYContributionsGrantsAmt>27459</irs:CYContributionsGrantsAmt>
      <irs:CYProgramServiceRevenueAmt>0</irs:CYProgramServiceRevenueAmt>
      <irs:CYInvestmentIncomeAmt>0</irs:CYInvestmentIncomeAmt>
      <irs:CYOtherRevenueAmt>0</irs:CYOtherRevenueAmt>
      <irs:CYTotalRevenueAmt>27459</irs:CYTotalRevenueAmt>
      <irs:CYGrantsAndSimilarPaidAmt>0</irs:CYGrantsAndSimilarPaidAmt>
      <irs:CYBenefitsPaidToMembersAmt>0</irs:CYBenefitsPaidToMembersAmt>
      <irs:CYSalariesCompEmpBnftPaidAmt>0</irs:CYSalariesCompEmpBnftPaidAmt>
      <irs:CYTotalProfFndrsngExpnsAmt>0</irs:CYTotalProfFndrsngExpnsAmt>
      <irs:CYTotalFundraisingExpenseAmt>0</irs:CYTotalFundraisingExpenseAmt>
      <irs:CYOtherExpensesAmt>27435</irs:CYOtherExpensesAmt>
      <irs:CYTotalExpensesAmt>27435</irs:CYTotalExpensesAmt>
      <irs:CYRevenuesLessExpensesAmt>24</irs:CYRevenuesLessExpensesAmt>
      <irs:TotalAssetsEOYAmt>0</irs:TotalAssetsEOYAmt>
      <irs:TotalLiabilitiesEOYAmt>0</irs:TotalLiabilitiesEOYAmt>
      <irs:NetAssetsOrFundBalancesEOYAmt>0</irs:NetAssetsOrFundBalancesEOYAmt>
      <irs:MissionDesc>DREAM BUILDERS MISSION IS TO EQUIP ALL MEMBERS OF THE COMMUNITY LIVING IN POVERTY, TO ATTAIN SELF-DIGNITY, SELF- RELIANCE, SELF-SUFFICIENCY AND TO TRANSITION BACK TO MAINSTREAM SOCIETY.</irs:MissionDesc>
      <irs:SignificantNewProgramSrvcInd>false</irs:SignificantNewProgramSrvcInd>
      <irs:SignificantChangeInd>false</irs:SignificantChangeInd>
      <irs:Desc>THE ORGANIZATION HAS BEEN ABLE TO GET THE ATTENTION OF LOCAL FOOD BANKS THAT HAS DISTRIBUTED IN KIND DONATIONS TO ASSIT WITH THE MISSION. WITHIN LESS THAN A YEAR IT HAS RECEIVED OVER $150,000 IN SUPPLIES TO REACH THE POPULATION THAT IS BEING SERVED</irs:Desc>
      <irs:DescribedInSection501c3Ind referenceDocumentId="BX0101">false</irs:DescribedInSection501c3Ind>
      <irs:ScheduleBRequiredInd>false</irs:ScheduleBRequiredInd>
      <irs:PoliticalCampaignActyInd>false</irs:PoliticalCampaignActyInd>
      <irs:LobbyingActivitiesInd>false</irs:LobbyingActivitiesInd>
      <irs:SubjectToProxyTaxInd>false</irs:SubjectToProxyTaxInd>
      <irs:DonorAdvisedFundInd>false</irs:DonorAdvisedFundInd>
      <irs:ConservationEasementsInd>false</irs:ConservationEasementsInd>
      <irs:CollectionsOfArtInd>false</irs:CollectionsOfArtInd>
      <irs:CreditCounselingInd>false</irs:CreditCounselingInd>
      <irs:TempOrPermanentEndowmentsInd>false</irs:TempOrPermanentEndowmentsInd>
      <irs:ReportLandBuildingEquipmentInd>false</irs:ReportLandBuildingEquipmentInd>
      <irs:ReportInvestmentsOtherSecInd>false</irs:ReportInvestmentsOtherSecInd>
      <irs:ReportProgramRelatedInvstInd>false</irs:ReportProgramRelatedInvstInd>
      <irs:ReportOtherAssetsInd>false</irs:ReportOtherAssetsInd>
      <irs:ReportOtherLiabilitiesInd>false</irs:ReportOtherLiabilitiesInd>
      <irs:IncludeFIN48FootnoteInd>false</irs:IncludeFIN48FootnoteInd>
      <irs:IndependentAuditFinclStmtInd>false</irs:IndependentAuditFinclStmtInd>
      <irs:ConsolidatedAuditFinclStmtInd>false</irs:ConsolidatedAuditFinclStmtInd>
      <irs:SchoolOperatingInd>false</irs:SchoolOperatingInd>
      <irs:ForeignOfficeInd>false</irs:ForeignOfficeInd>
      <irs:ForeignActivitiesInd>false</irs:ForeignActivitiesInd>
      <irs:MoreThan5000KToOrgInd>false</irs:MoreThan5000KToOrgInd>
      <irs:MoreThan5000KToIndividualsInd>false</irs:MoreThan5000KToIndividualsInd>
      <irs:ProfessionalFundraisingInd>false</irs:ProfessionalFundraisingInd>
      <irs:FundraisingActivitiesInd>false</irs:FundraisingActivitiesInd>
      <irs:GamingActivitiesInd>false</irs:GamingActivitiesInd>
      <irs:OperateHospitalInd>false</irs:OperateHospitalInd>
      <irs:GrantsToOrganizationsInd>false</irs:GrantsToOrganizationsInd>
      <irs:GrantsToIndividualsInd>false</irs:GrantsToIndividualsInd>
      <irs:ScheduleJRequiredInd>false</irs:ScheduleJRequiredInd>
      <irs:TaxExemptBondsInd>false</irs:TaxExemptBondsInd>
      <irs:EngagedInExcessBenefitTransInd>false</irs:EngagedInExcessBenefitTransInd>
      <irs:PYExcessBenefitTransInd>false</irs:PYExcessBenefitTransInd>
      <irs:LoanOutstandingInd>false</irs:LoanOutstandingInd>
      <irs:GrantToRelatedPersonInd>false</irs:GrantToRelatedPersonInd>
      <irs:BusinessRlnWithOrgMemInd>false</irs:BusinessRlnWithOrgMemInd>
      <irs:BusinessRlnWithFamMemInd>false</irs:BusinessRlnWithFamMemInd>
      <irs:BusinessRlnWithOfficerEntInd>false</irs:BusinessRlnWithOfficerEntInd>
      <irs:DeductibleNonCashContriInd>false</irs:DeductibleNonCashContriInd>
      <irs:DeductibleArtContributionInd>false</irs:DeductibleArtContributionInd>
      <irs:TerminateOperationsInd>false</irs:TerminateOperationsInd>
      <irs:PartialLiquidationInd>false</irs:PartialLiquidationInd>
      <irs:DisregardedEntityInd>false</irs:DisregardedEntityInd>
      <irs:RelatedEntityInd>false</irs:RelatedEntityInd>
      <irs:RelatedOrganizationCtrlEntInd>false</irs:RelatedOrganizationCtrlEntInd>
      <irs:TrnsfrExmptNonChrtblRltdOrgInd>false</irs:TrnsfrExmptNonChrtblRltdOrgInd>
      <irs:ActivitiesConductedPrtshpInd>false</irs:ActivitiesConductedPrtshpInd>
      <irs:ScheduleORequiredInd>false</irs:ScheduleORequiredInd>
      <irs:IRPDocumentCnt>0</irs:IRPDocumentCnt>
      <irs:IRPDocumentW2GCnt>0</irs:IRPDocumentW2GCnt>
      <irs:EmployeeCnt>0</irs:EmployeeCnt>
      <irs:UnrelatedBusIncmOverLimitInd>false</irs:UnrelatedBusIncmOverLimitInd>
      <irs:ForeignFinancialAccountInd>false</irs:ForeignFinancialAccountInd>
      <irs:ProhibitedTaxShelterTransInd>false</irs:ProhibitedTaxShelterTransInd>
      <irs:TaxablePartyNotificationInd>false</irs:TaxablePartyNotificationInd>
      <irs:NondeductibleContributionsInd>false</irs:NondeductibleContributionsInd>
      <irs:IndoorTanningServicesInd>false</irs:IndoorTanningServicesInd>
      <irs:InfoInScheduleOPartVIInd>X</irs:InfoInScheduleOPartVIInd>
      <irs:GoverningBodyVotingMembersCnt>0</irs:GoverningBodyVotingMembersCnt>
      <irs:IndependentVotingMemberCnt>0</irs:IndependentVotingMemberCnt>
      <irs:FamilyOrBusinessRlnInd>false</irs:FamilyOrBusinessRlnInd>
      <irs:DelegationOfMgmtDutiesInd>false</irs:DelegationOfMgmtDutiesInd>
      <irs:ChangeToOrgDocumentsInd>false</irs:ChangeToOrgDocumentsInd>
      <irs:MaterialDiversionOrMisuseInd>false</irs:MaterialDiversionOrMisuseInd>
      <irs:MembersOrStockholdersInd>false</irs:MembersOrStockholdersInd>
      <irs:ElectionOfBoardMembersInd>false</irs:ElectionOfBoardMembersInd>
      <irs:DecisionsSubjectToApprovaInd>false</irs:DecisionsSubjectToApprovaInd>
      <irs:MinutesOfGoverningBodyInd>true</irs:MinutesOfGoverningBodyInd>
      <irs:MinutesOfCommitteesInd>true</irs:MinutesOfCommitteesInd>
      <irs:OfficerMailingAddressInd>false</irs:OfficerMailingAddressInd>
      <irs:LocalChaptersInd>false</irs:LocalChaptersInd>
      <irs:Form990ProvidedToGvrnBodyInd>true</irs:Form990ProvidedToGvrnBodyInd>
      <irs:ConflictOfInterestPolicyInd>true</irs:ConflictOfInterestPolicyInd>
      <irs:AnnualDisclosureCoveredPrsnInd>false</irs:AnnualDisclosureCoveredPrsnInd>
      <irs:RegularMonitoringEnfrcInd>false</irs:RegularMonitoringEnfrcInd>
      <irs:WhistleblowerPolicyInd>true</irs:WhistleblowerPolicyInd>
      <irs:DocumentRetentionPolicyInd>true</irs:DocumentRetentionPolicyInd>
      <irs:CompensationProcessCEOInd>true</irs:CompensationProcessCEOInd>
      <irs:CompensationProcessOtherInd>true</irs:CompensationProcessOtherInd>
      <irs:InvestmentInJointVentureInd>false</irs:InvestmentInJointVentureInd>
      <irs:StatesWhereCopyOfReturnIsFldCd>FL</irs:StatesWhereCopyOfReturnIsFldCd>
      <irs:BooksInCareOfDetail>
        <irs:PersonNm>HARRISON SOBERANIS</irs:PersonNm>
        <irs:PhoneNum>8134451697</irs:PhoneNum>
        <irs:USAddress>
          <irs:AddressLine1Txt>8145 NEBRASKA AVENUE</irs:AddressLine1Txt>
          <irs:CityNm>TAMPA</irs:CityNm>
          <irs:StateAbbreviationCd>FL</irs:StateAbbreviationCd>
          <irs:ZIPCd>33604</irs:ZIPCd>
        </irs:USAddress>
      </irs:BooksInCareOfDetail>
      <irs:NoListedPersonsCompensatedInd>X</irs:NoListedPersonsCompensatedInd>
      <irs:Form990PartVIISectionAGrp>
        <irs:PersonNm>HARRISON SOBERANIS</irs:PersonNm>
        <irs:TitleTxt>EXECUTIVE DIRECTOR</irs:TitleTxt>
        <irs:AverageHoursPerWeekRt>0</irs:AverageHoursPerWeekRt>
        <irs:AverageHoursPerWeekRltdOrgRt>0</irs:AverageHoursPerWeekRltdOrgRt>
        <irs:ReportableCompFromOrgAmt>0</irs:ReportableCompFromOrgAmt>
        <irs:ReportableCompFromRltdOrgAmt>0</irs:ReportableCompFromRltdOrgAmt>
        <irs:OtherCompensationAmt>0</irs:OtherCompensationAmt>
      </irs:Form990PartVIISectionAGrp>
      <irs:FormerOfcrEmployeesListedInd>false</irs:FormerOfcrEmployeesListedInd>
      <irs:TotalCompGreaterThan150KInd>false</irs:TotalCompGreaterThan150KInd>
      <irs:CompensationFromOtherSrcsInd>false</irs:CompensationFromOtherSrcsInd>
      <irs:AllOtherContributionsAmt>27459</irs:AllOtherContributionsAmt>
      <irs:NoncashContributionsAmt>204500</irs:NoncashContributionsAmt>
      <irs:TotalContributionsAmt>27459</irs:TotalContributionsAmt>
      <irs:NetIncmFromFundraisingEvtGrp>
        <irs:TotalRevenueColumnAmt>0</irs:TotalRevenueColumnAmt>
      </irs:NetIncmFromFundraisingEvtGrp>
      <irs:TotalRevenueGrp>
        <irs:TotalRevenueColumnAmt>27459</irs:TotalRevenueColumnAmt>
        <irs:RelatedOrExemptFuncIncomeAmt>0</irs:RelatedOrExemptFuncIncomeAmt>
        <irs:UnrelatedBusinessRevenueAmt>0</irs:UnrelatedBusinessRevenueAmt>
        <irs:ExclusionAmt>0</irs:ExclusionAmt>
      </irs:TotalRevenueGrp>
      <irs:OtherExpensesGrp>
        <irs:Desc>OPERATING EXPENSES</irs:Desc>
        <irs:TotalAmt>1067</irs:TotalAmt>
      </irs:OtherExpensesGrp>
      <irs:OtherExpensesGrp>
        <irs:Desc>RENT</irs:Desc>
        <irs:TotalAmt>15600</irs:TotalAmt>
        <irs:ManagementAndGeneralAmt>15600</irs:ManagementAndGeneralAmt>
      </irs:OtherExpensesGrp>
      <irs:OtherExpensesGrp>
        <irs:Desc>TELEPHONE AND INTERNET</irs:Desc>
        <irs:TotalAmt>2400</irs:TotalAmt>
        <irs:ManagementAndGeneralAmt>2400</irs:ManagementAndGeneralAmt>
      </irs:OtherExpensesGrp>
      <irs:OtherExpensesGrp>
        <irs:Desc>UTILITIES</irs:Desc>
        <irs:TotalAmt>6868</irs:TotalAmt>
        <irs:ManagementAndGeneralAmt>6868</irs:ManagementAndGeneralAmt>
      </irs:OtherExpensesGrp>
      <irs:AllOtherExpensesGrp>
        <irs:TotalAmt>1500</irs:TotalAmt>
        <irs:ManagementAndGeneralAmt>1500</irs:ManagementAndGeneralAmt>
      </irs:AllOtherExpensesGrp>
      <irs:TotalFunctionalExpensesGrp>
        <irs:TotalAmt>27435</irs:TotalAmt>
        <irs:ProgramServicesAmt>0</irs:ProgramServicesAmt>
        <irs:ManagementAndGeneralAmt>26368</irs:ManagementAndGeneralAmt>
        <irs:FundraisingAmt>0</irs:FundraisingAmt>
      </irs:TotalFunctionalExpensesGrp>
      <irs:TotalAssetsGrp>
        <irs:BOYAmt>0</irs:BOYAmt>
        <irs:EOYAmt>0</irs:EOYAmt>
      </irs:TotalAssetsGrp>
      <irs:TotalLiabilitiesGrp>
        <irs:BOYAmt>0</irs:BOYAmt>
        <irs:EOYAmt>0</irs:EOYAmt>
      </irs:TotalLiabilitiesGrp>
      <irs:OrganizationFollowsSFAS117Ind>X</irs:OrganizationFollowsSFAS117Ind>
      <irs:TotalNetAssetsFundBalanceGrp>
        <irs:BOYAmt>0</irs:BOYAmt>
        <irs:EOYAmt>0</irs:EOYAmt>
      </irs:TotalNetAssetsFundBalanceGrp>
      <irs:TotLiabNetAssetsFundBalanceGrp>
        <irs:BOYAmt>0</irs:BOYAmt>
        <irs:EOYAmt>0</irs:EOYAmt>
      </irs:TotLiabNetAssetsFundBalanceGrp>
      <irs:ReconcilationRevenueExpnssAmt>24</irs:ReconcilationRevenueExpnssAmt>
      <irs:MethodOfAccountingCashInd>X</irs:MethodOfAccountingCashInd>
      <irs:AccountantCompileOrReviewInd>true</irs:AccountantCompileOrReviewInd>
      <irs:AcctCompileOrReviewBasisGrp>
        <irs:SeparateBasisFinclStmtInd>X</irs:SeparateBasisFinclStmtInd>
      </irs:AcctCompileOrReviewBasisGrp>
      <irs:FSAuditedInd>true</irs:FSAuditedInd>
      <irs:FSAuditedBasisGrp>
        <irs:SeparateBasisFinclStmtInd>X</irs:SeparateBasisFinclStmtInd>
      </irs:FSAuditedBasisGrp>
      <irs:AuditCommitteeInd>true</irs:AuditCommitteeInd>
      <irs:FederalGrantAuditRequiredInd>false</irs:FederalGrantAuditRequiredInd>
    </irs:IRS990>
    <irs:IRS990ScheduleA documentId="BX0101">
      <irs:PubliclySupportedOrg509a2Ind>X</irs:PubliclySupportedOrg509a2Ind>
      <irs:GrossReceiptsRltdActivitiesAmt>1090</irs:GrossReceiptsRltdActivitiesAmt>
      <irs:GiftsGrantsContrisRcvd509Grp>
        <irs:CurrentTaxYearAmt>27459</irs:CurrentTaxYearAmt>
        <irs:TotalAmt>27459</irs:TotalAmt>
      </irs:GiftsGrantsContrisRcvd509Grp>
      <irs:Total509Grp>
        <irs:CurrentTaxYearAmt>27459</irs:CurrentTaxYearAmt>
        <irs:TotalAmt>27459</irs:TotalAmt>
      </irs:Total509Grp>
      <irs:PublicSupportTotal509Amt>27459</irs:PublicSupportTotal509Amt>
      <irs:TotalSupportCalendarYearGrp>
        <irs:CurrentTaxYearAmt>27459</irs:CurrentTaxYearAmt>
        <irs:TotalAmt>27459</irs:TotalAmt>
      </irs:TotalSupportCalendarYearGrp>
      <irs:PublicSupportCY509Pct>1.00000</irs:PublicSupportCY509Pct>
      <irs:InvestmentIncomeCYPct>0</irs:InvestmentIncomeCYPct>
      <irs:ThirtyThrPctSuprtTestsCY509Ind>X</irs:ThirtyThrPctSuprtTestsCY509Ind>
    </irs:IRS990ScheduleA>
    <irs:IRS990ScheduleO documentId="BX1501">
      <irs:SupplementalInformationDetail>
        <irs:FormAndLineReferenceDesc>990, Part VI, Line 8a</irs:FormAndLineReferenceDesc>
        <irs:ExplanationTxt>ALL MEETINGS WILL BE RECORDED</irs:ExplanationTxt>
      </irs:SupplementalInformationDetail>
      <irs:SupplementalInformationDetail>
        <irs:FormAndLineReferenceDesc>990, Part VI, Line 8b</irs:FormAndLineReferenceDesc>
        <irs:ExplanationTxt>MEETING MINUTES ARE AVAILABLE FOR THE GOVERNING BODY TO REVIEW</irs:ExplanationTxt>
      </irs:SupplementalInformationDetail>
      <irs:SupplementalInformationDetail>
        <irs:FormAndLineReferenceDesc>990, Part VI, Line 11b</irs:FormAndLineReferenceDesc>
        <irs:ExplanationTxt>A COMPLETED FOR 990 IS PREPARED AND FURNISHED TO MR SOBERANIS PRIOR TO FILING. DISCUSSIONS ARE DONE BETWEEN CPA AND MR SOBERANIS TO DISCUSS AT LENGTHS.</irs:ExplanationTxt>
      </irs:SupplementalInformationDetail>
      <irs:SupplementalInformationDetail>
        <irs:FormAndLineReferenceDesc>990, Part VI, Line 15</irs:FormAndLineReferenceDesc>
        <irs:ExplanationTxt>THE ORGANIZATION CURRENTLY PAYS NO COMPENSATION TO THE BOARD OR ITS MEMBER. HOWEVER THE ORGANIZATION WILL DISCUSS WITH VOTING MEMBERS AND BOARD WHEN THE NEED ARISES.</irs:ExplanationTxt>
      </irs:SupplementalInformationDetail>
      <irs:SupplementalInformationDetail>
        <irs:FormAndLineReferenceDesc>990, Part VI, Line 19</irs:FormAndLineReferenceDesc>
        <irs:ExplanationTxt>A COPY OF THE ORGANIZATION'S 990 IS AVAILABLE UPON REQUEST</irs:ExplanationTxt>
      </irs:SupplementalInformationDetail>
    </irs:IRS990ScheduleO>
  </irs:ReturnData>
</irs:Return>
```

**Comment by jsfenfen** [comment]
Thank you for flagging this @fgregg. Taking a look. I believe there are schemas available for TY 2017, lemme look into this a bit more.

**Comment by jsfenfen** [comment]
Actually, this is weirder than that--it appears that all the tags are prefixed with "irs:" which is legal-ish in xml, maybe, but hasn't occurred in practice. It can't find "Return" because the text is actually "irs:Return".   I'm not aware of other files that have tags like this, so unclear if it's a one-off, or whether this was always valid, or whether this is a new way of filing... 

@fgregg have you seen this elsewhere?  I'm gonna look into just removing the leading "irs:" if it's present, but unclear why it's now showing up.

As a test I removed the "irs:" parts from the file and it ran, but this needs an actual fix, probably

**Comment by jsfenfen** [comment]
Ok, it sounds like stripping the namespaces is the way to go.

**Comment by jsfenfen** [comment]
Thanks again for the report @fgregg I think this should work with irsx updated to 0.2.5:
https://github.com/jsfenfen/990-xml-reader/releases
