### ISSUE TITLE
MySQL "Duplicate column name 'AppldTESTxAmt'

### ISSUE THREAD

**Issue by rabsef-bicrym** [jsfenfen/990-xml-database#30]
As it turns out my purpose is not fulfilled using postgresql because of a known incompatibility between my visualization studio and postgresql 12.  A shame.  I'm getting an error now in `python3 manage.py migrate return` at 
```
Running migrations:
  Applying return.0001_initial...Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
  File "/home/eric/.local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/eric/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/eric/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/eric/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1060, "Duplicate column name 'AppldTESTxAmt'")
```

It might have been something I've done but could you let me know if that seems odd or potentially based on something in the code?

Sorry - I'm going to kill the server and try again, notwithstanding to see if I missed a step somewhere or duplicated a step, etc.

**Comment by jsfenfen** [comment]
Hi @rabsef-bicrym you are probably seeing problems because mysql is case insensitive, in other words, there's probably a variable with the same letters and different capitalization. I've gotten it working in mysql by changing the capitalization but it's not straightforward because it relies on the metadata files in irsx at that location. I haven't fixed it because changing it is backwards incompatible--I'd urge you to work with postgresql for this reason.
